# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Michael S. Totty"                                # Your name
  description: "Research Scientist at the Lieber Institute for Brain Development, working at the intersection of molecular, computational, and systems neuroscience."
  image: img/michael_totty.png
  favicon: img/favicon.svg
  site-url: https://MicTott.github.io/
  open-graph: true
  twitter-card:
    card-style: summary

  # start of the navigation bar at the top of the website
  navbar:
    pinned: true

    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Software & Data"
        href: software/index.qmd
      - text: "CV"
        href: cv/index.qmd




# Don't touch unless you know what you are doing :) ------------
  search:
    location: navbar
    type: textbox
  page-footer:
    left: |
      <span class="faux-block">&#169; 2026 Michael S. Totty CC BY-SA 4.0</span>
#    right: |
#      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    description-meta: "Research Scientist at the Lieber Institute for Brain Development, working at the intersection of molecular, computational, and systems neuroscience."
    fontsize: 0.9em
    mainfont: "Roboto"
    theme:
      light:
        - lux
        - html/styles.scss
      dark:
        - darkly
        - html/styles-dark.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    page-layout: full
